version: '3.9'

volumes:
  app_database: {}

networks:
  sensitive-serializer-dbal-network:
    name: sensitive-serializer-dbal-network
    driver: bridge

services:

  broadway-sensitive-serializer-dbal-php:
    image: broadway-sensitive-serializer-dbal-php
    build: php
    hostname: sensitive_serializer_dbal
    volumes:
      - ../:/var/www/app:delegated
      - ./data/shell_history:/home/utente/shell_history
    networks:
      - sensitive-serializer-dbal-network
    environment:
      - HISTFILE=/home/utente/shell_history/.x_history
    secrets:
      - source: id_rsa
        target: /home/utente/.ssh/id_rsa
      - source: id_rsa.pub
        target: /home/utente/.ssh/id_rsa.pub
      - source: known_hosts
        target: /home/utente/.ssh/known_hosts

  broadway-sensitive-serializer-dbal-nodejs:
    image: broadway-sensitive-serializer-dbal-nodejs
    build: nodejs
    working_dir: /var/www/app
    volumes:
      - ../:/var/www/app
    networks:
      - sensitive-serializer-dbal-network