version: '3.9'

secrets:
  id_rsa:
    file: ~/.ssh/mado
  id_rsa.pub:
    file: ~/.ssh/mado.pub
  known_hosts:
    file: ~/.ssh/known_hosts

services:

  php_broadway_sensitive_serializer_dbal:
    environment:
      - AGGREGATE_MASTER_KEY="SS3kr3tK31"

#  servicedb:
#    ports:
#      - "3310:3306"